### ISSUE TITLE
Alex Intro 0.3 Assignment

### ISSUE THREAD

**Issue by AlexD017** [Dylanluo05/Daji-Coders#5]
- Picture with Mask that toggles to Picture of Choice (ie pic without mask)
- Pull or show data (Web API) with information of interest
- Establish link(s) to journal and other key indicators of your work and progress (remember pop quiz)

**Comment by jeankim05** [comment]
[Link to commit as tangible](https://github.com/Dylanluo05/Daji-Coders/commit/4a23f6585ee399b8e96d5a3d523fa4eaea72a04f)
