### ISSUE TITLE
Week 4 Review - Dylan

### ISSUE THREAD

**Issue by jeankim05** [Dylanluo05/Daji-Coders#50]

**Comment by jeankim05** [comment]
[Link to Time Box for Week 4](https://github.com/Dylanluo05/Daji-Coders/blob/main/README.md#sprint-4-week-4)
[Link to Scrum Board Ticket](https://github.com/Dylanluo05/Daji-Coders/issues/46)
[Link to Scrum Board Ticket](https://github.com/Dylanluo05/Daji-Coders/issues/53)

Practice AP MCQ Test Score: 64/67

**Comment by Dylanluo05** [comment]
4.5/5: I finished all of my tasks for the week and I contributed a lot to the team. However, I could have experimented more on other programming languages such as Bootstrap and Crud, so I believe I should get 0.5 points docked off my score.
