### ISSUE TITLE
Week 4 Review - Isabelle

### ISSUE THREAD

**Issue by jeankim05** [Dylanluo05/Daji-Coders#51]

**Comment by jeankim05** [comment]
[Link to Time Box for Week 4](https://github.com/Dylanluo05/Daji-Coders/blob/main/README.md#sprint-4-week-4)
[Link to Scrum Board Ticket](https://github.com/Dylanluo05/Daji-Coders/issues/32)

Practice AP MCQ Test Score: 63/67

**Comment by isabelle926** [comment]
Score: 4.75/5

Got full points for being engaged in class, being able to demonstrate understanding of javascript/python and learning CSS/HTML, discussed Currency Exchange page and future plans during review. 

For Currency Exchange, create a dropdown for the converter and move the calculator to the top of the page. 

Planning to work on searchbar with Jean, learn more CSS from Dylan, and format the search results in the SQL Search page.
