### ISSUE TITLE
Week 4 Review - Alex

### ISSUE THREAD

**Issue by jeankim05** [Dylanluo05/Daji-Coders#52]

**Comment by jeankim05** [comment]
[Link to Time Box for Week 4](https://github.com/Dylanluo05/Daji-Coders/blob/main/README.md#sprint-4-week-4)
[Link to Scrum Board Ticket](https://github.com/Dylanluo05/Daji-Coders/issues/48)

Practice AP MCQ Test Score: 64/67

**Comment by AlexD017** [comment]
Score: 4/5

Fully engaged in class, deployed team repository README as GitHub Page, but need to change github.io domain into subdomain. Demonstrated CarSearch Page during review with search bar autocomplete function, try working on Python CSS or Python coding as a whole. Need more coding than focusing on deployment role.
