### ISSUE TITLE
Jean Week 11 Review ticket PBL Final

### ISSUE THREAD

**Issue by jeankim05** [Dylanluo05/Daji-Coders#79]
# Week 11 PBL Final Individual Score Self Grade for Jean - 9/10
# Week 11 PBL Final Individual Score Crossover Grade by Noah for Jean - 9/10

**Comment by jeankim05** [comment]
**Create Task Project Individual/Pair Evaluation**

Wiki Pages with design ideas and usage
[Jean and Isabelle](https://github.com/Dylanluo05/Daji-Coders/wiki/Week-9-Assignment-Create-Task:-Food-Quiz)
[Dylan and Alex](https://github.com/Dylanluo05/Daji-Coders/wiki/Week-9-Create-Task-Programming)

Create Performance Task PBL Feature
[Link to deployed website](https://dajicoders.tk/)
-   Foodie Finder for Jean and Isabelle
-   Travel Recommendations for Dylan and Alex

Final Committed Program Code
[Jean and Isabelle](https://github.com/Dylanluo05/Daji-Coders/blob/main/templates/foodquiz.html)
[Dylan and Alex](https://github.com/Dylanluo05/Daji-Coders/blob/main/templates/TravelRecommendation.html)

Written Responses to all prompts in the performance task (wiki pages contain written responses and overview)
[Jean and Isabelle](https://github.com/Dylanluo05/Daji-Coders/wiki/Week-9-Assignment-Create-Task:-Food-Quiz)
[Dylan and Alex](https://github.com/Dylanluo05/Daji-Coders/wiki/Week-9-Create-Task-Programming)

1 Minute Video
[Jean](https://www.youtube.com/watch?v=9elTx5q5-Ps)
[Isabelle](https://www.loom.com/share/974ab7acd8d24327b08b3eecf9ac5882)
[Dylan](https://drive.google.com/file/d/1piu1iX_sbpnTOrTOUmOj6HkTRWtmJT8Y/view)
[Alex](https://photos.google.com/share/AF1QipNkRvLbtZ6hCRKXyKIHPY0EtQsLnDnEddG-0hfy2Djc9tsTAZ5XuA3vE7V1sur5wg/photo/AF1QipN6liiORj05_VWDeOZiNpNWDIUlEY6ycZBjZG6F?key=MFM0S0NJVDYtTF9oVlBsN2p2aGhfY3hQVVlrUUF3)

**Team Final Grading Considerations**

PBL Github Pages
[Github Pages](http://dajipages.dajicoders.tk/)

Runtime Features 1 Minute video
[Link to video](https://drive.google.com/file/d/1U1rls6oC3NJ0CeQgZDIz7sgrxVzb2T7f/view)

Clarity and Quality of Finding Information
[Link to organized README](https://github.com/Dylanluo05/Daji-Coders/blob/main/README.md)
[Link to organized Scrum Board](https://github.com/Dylanluo05/Daji-Coders/projects/1)

Deployed Project
[Link to deployed project](https://dajicoders.tk/)

Night At the Museum Participation and Readiness
[Link to deployed project that we are presenting](https://dajicoders.tk/)

**Self Grades**
Jean - 9/10
Dylan - 9/10
Isabelle - 9/10
Alex - 8.8/10
(Check above for all requirements)
Deductions
-1 for missing SCSS, Crud Asynch not completely working and imported, PBL theme not consistent throughout project (everyone)
-0.2 for Alex for missing blueprints

**Comment by jeankim05** [comment]
Self Grades
Jean - 9/10
Dylan - 9/10
Isabelle - 9/10
Alex - 8.8/10

**Comment by NoahJ214** [comment]
Jean Week 11 PBL Final Peer Grade: 9/10

-Wiki/Jekyll page with design ideas and usage: 1/1 
[Wiki Page](https://github.com/Dylanluo05/Daji-Coders/wiki/Week-9-Assignment-Create-Task:-Food-Quiz)

-Create Performance Task PBL feature 1/1
[Deployed Website](https://dajicoders.tk/)

-Final committed program code showing algorithms written in JS/Python 1/1
[Program Code](https://github.com/Dylanluo05/Daji-Coders/blob/main/templates/foodquiz.html)

-Written responses to all the prompts in the performance task 1/1
[Written responses](https://github.com/Dylanluo05/Daji-Coders/wiki/Week-9-Assignment-Create-Task:-Food-Quiz)

-1min video that meets CB create task requirements 1/1
[Link to 1 min video](https://www.youtube.com/watch?v=9elTx5q5-Ps)

-PBL Github pages. Jekyll, WIKI, live review focus 0/1
[Github Pages](http://dajipages.dajicoders.tk/)

-Runtime Features shown in 1 min video 1/1
[Runtime video](https://drive.google.com/file/d/1U1rls6oC3NJ0CeQgZDIz7sgrxVzb2T7f/view)

-Clarity and quality of finding information 1/1
[Organized ReadME](https://github.com/Dylanluo05/Daji-Coders/blob/main/README.md)
[Organized Scrumboard](https://github.com/Dylanluo05/Daji-Coders/projects/1)

-Deployed Project 24/7 - Deployment Overview and Policies in Github Pages 1/1
[Deployed Project](https://dajicoders.tk/)

-[N@tM](mailto:N@tM) Participation and readiness for event 1/1
[Deployed Project that they will present](https://dajicoders.tk/)

Deductions: 
-0.5 CRUD/Async not working 
-0.25 PBL Theme not consistent
-0.25 Missing Sassy
