### ISSUE TITLE
Isabelle Week 11 Review Ticket

### ISSUE THREAD

**Issue by isabelle926** [Dylanluo05/Daji-Coders#80]
### Crossover grade: 9/10

Link to create task review ticket: [Link](https://github.com/Dylanluo05/Daji-Coders/issues/79)

**Comment by dtsivkovski** [comment]
# Final Score: 9/10

### Individual/Pair Evaluation on Create Task Project - 4/5pts


- [x] Wiki/Jekyll page with design ideas and usage - _Wiki page is [present](https://github.com/Dylanluo05/Daji-Coders/wiki/Week-9-Assignment-Create-Task:-Food-Quiz) with complete description of the task._
- [x] Create Performance Task PBL feature - _This fits with their travel theme of their website and is useful._
- [x] Final committed program code showing algorithms written in JS/Python - _The program is written in JS, the code can also be examined through inspect element on the runtime._
- [ ] Written responses to all the prompts in the performance task - _Not present, the written responses are not complete on the create task page and are also not done individually_ 
- [x] 1min video that meets CB create task requirements - _Present and shows the create task's function/how it works_


### Team Final Grading - 5/5 pts.


#### PBL Github pages. Jekyll, WIKI, live review focusc
- [x] PBL theme consistent through project and described in Github Pages -  _Both are complete and the theme of the project is clear on the deployed site._
- [x] Sassy / Bootstrap - _Clear that the project uses custom scss and bootstrap throughout, with a theme that is consistent._
- [x] Blueprint illustration/demonstration - _[Blueprinting is present](https://github.com/Dylanluo05/Daji-Coders/blob/main/main.py#L6) in the project with the different routing being organized_
- [x] CRUD Async Operation - runtime and understanding of JavaScript and Fetch - _Their group has a database that has a search feature and crud entry._
- [x] Individual PBL MVC feature/commits showing algorithms written in JS/Python  - _Isabelle worked on the database search feature with the JS fetch function._

#### Runtime Features shown in 1 min video
- [x] Highlight of best features -  _Shows off the team's features related to their travel theme. _ 
- [x] CRUD/Search on project database tables, easy to identify from UI - _CRUD and search is present on the project, although slightly rudimentary._
- [x] MVC - a code overview showing usage of MVC (HTML, Routes/Render Template functions, Model functions) - _They provide a view of the search function which pulls information from the database._
- [x] Google Search or Google translate implemented - _The group has a Google Translate feature implemented on their navbar._
- [x] Scrum Board - Overview of completed tasks and Github tangibles - _The scrum board is shown in the video and it is neatly organized._
