### ISSUE TITLE
Dylan Luo Review Ticket

### ISSUE THREAD

**Issue by Dylanluo05** [Dylanluo05/Daji-Coders#81]
### Overall Score Graded By Crossover: 9.4/10

**Individual/Pair Evaluation on Create Task Project - 5pts**

- [ ] Wiki/Jekyll page with design ideas and usage

- [ ] Create Performance Task PBL feature

- [ ] Final committed program code showing algorithms written in JS/Python

- [ ] Written responses to all the prompts in the performance task

- [ ] 1min video that meets CB create task requirements 

**Team Final Grading Considerations - 5 pts**

- [ ] PBL Github pages. Jekyll, WIKI, live review focus

- [ ] PBL theme consistent through project and described in Github Pages

- [ ] Sassy / Bootstrap

- [ ] Blueprint illustration/demonstration

- [ ] CRUD Async Operation - runtime and understanding of JavaScript and Fetch

- [ ] Individual PBL MVC feature/commits showing algorithms written in JS/Python 

**Runtime Features shown in 1 min video**

- [ ] Highlight of best features

- [ ] CRUD/Search on project database tables, easy to identify from UI

- [ ] MVC - a code overview showing usage of MVC (HTML, Routes/Render Template functions, Model functions)

- [ ] Google Search or Google translate implemented 

- [ ] Scrum Board - Overview of completed tasks and Github tangibles

**Comment by Pitsco** [comment]
Overall Score: 9.4/10

Overall, very good. The only two concerns I had were his written responses and video. His written responses were not detailed enough and didn't link many examples. Also, the video went a bit over time and didn't have clear explanations so I would recommend using captions to clarify what is going on.
