### ISSUE TITLE
Alex Do -Week 11 Review Ticket

### ISSUE THREAD

**Issue by AlexD017** [Dylanluo05/Daji-Coders#82]
### Overall 9.5/10 
**Individual/Pair Evaluation on Create Task Project - 5pts**

 

- [x] Wiki/Jekyll page with design ideas and usage

 

- [x] Create Performance Task PBL feature

- [x]  Final committed program code showing algorithms written in JS/Python

- [x]  Written responses to all the prompts in the performance task

- [x]  1min video that meets CB create task requirements

**Team Final Grading Considerations - 5 pts**

- [x]  PBL Github pages. Jekyll, WIKI, live review focus

- [x] PBL theme consistent through project and described in Github Pages

- [x] Sassy / Bootstrap

- [ ] Blueprint illustration/demonstration

- [ ] CRUD Async Operation - runtime and understanding of JavaScript and Fetch

- [ ] Individual PBL MVC feature/commits showing algorithms written in JS/Python

- [x]  Runtime Features shown in 1 min video

- [x] Highlight of best features

- [ ] CRUD/Search on project database tables, easy to identify from UI

- [x] MVC - a code overview showing usage of MVC (HTML, Routes/Render Template functions, Model functions)

- [x] Google Search or Google translate implemented

- [x] Scrum Board - Overview of completed tasks and Github tangibles

- [x]  Clarity and quality of finding information 

- [x]  Deployed Project 24/7 - Deployment Overview and Policies in Github Pages

- [x]  [N@tM](mailto:N@tM) Participation and readiness for event

**Comment by Reinhardtlotter** [comment]
9.5 Good code and PBL features but short written response answers other bullets were all hit and completed. Videos show the runtime good and I was able to see everything and all the requirements were displayed. All I suggest is expand on the written responses. All questions must be answered in detail for CB credit on the exam.
Individual/Pair Evaluation on Create Task Project - 5pts

 

- [x] Wiki/Jekyll page with design ideas and usage


- [x]  Create Performance Task PBL feature

 

- [x] Final committed program code showing algorithms written in JS/Python

 

- [x] Written responses to all the prompts in the performance task  (ONLY HALF POINT GIVEN HERE)

- [x]  1min video that meets CB create task requirements

Team Final Grading Considerations - 5 pts

 PBL Github pages. Jekyll, WIKI, live review focus

 

- [x] PBL theme consistent through project and described in Github Pages

 

- [x] Sassy / Bootstrap

- [x]  Blueprint illustration/demonstration

 

- [x] CRUD Async Operation - runtime and understanding of JavaScript and Fetch

- [x]  Individual PBL MVC feature/commits showing algorithms written in JS/Python

 Runtime Features shown in 1 min video

- [x]  Highlight of best features

 

- [x] CRUD/Search on project database tables, easy to identify from UI

 

- [x] MVC - a code overview showing usage of MVC (HTML, Routes/Render Template functions, Model functions)

 

- [x] Google Search or Google translate implemented

 

- [x] Scrum Board - Overview of completed tasks and Github tangibles
